import Head from 'next/head'
import { motion } from 'framer-motion'
import Link from 'next/link'

export default function Home() {
    return (
        <>
            <motion.div exit={{ opacity: 0 }}>
                <Head>
                    <title>Nils Arndt</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="container grid p-4 mx-auto -m-20 text-gray-700 page-vertical-center">
                    <div>
                        <div className="grid mb-24 tracking-wide text-center justify-self-center">
                            <p className="mb-4 text-6xl font-medium">
                                My Name is
                                <span> </span>
                                <span className="underline decoration-orange-500">Nils Arndt</span>.
                            </p>
                            <p className="text-2xl">Finance + Data Science + Programming</p>
                        </div>
                        <div className="flex items-center text-white md:h-full">
                            <div className="flex flex-wrap -m-4">
                                <Link href="/aboutme" className="p-4 sm:w-1/2 lg:w-1/4">
                                    <motion.div
                                        whileHover={{ scale: 1.05, rotate: 2, y: -40 }}
                                        whileTap={{ scale: 0.95 }}
                                    >
                                        <div className="h-full overflow-hidden border-2 border-gray-200 rounded-lg group border-opacity-60 hover:ring-red-500 hover:ring-4 hover:ring-offset-4 hover:cursor-pointer">
                                            <img
                                                className="object-cover object-center w-full lg:h-72 md:h-48"
                                                src="https://i.imgur.com/N5unMGM.jpeg"
                                                alt=""
                                            />
                                            <div className="p-6 bg-red-500">
                                                <h1 className="mb-3 text-2xl font-semibold">
                                                    About Me
                                                </h1>
                                                <p className="mb-3 leading-relaxed">
                                                    Vita, Experiences & Roadmap
                                                </p>
                                            </div>
                                        </div>
                                    </motion.div>
                                </Link>
                                <Link href="/projects" className="p-4 sm:w-1/2 lg:w-1/4">
                                    <motion.div
                                        whileHover={{ scale: 1.05, rotate: 1, y: -30 }}
                                        whileTap={{ scale: 0.95 }}
                                    >
                                        <div className="h-full overflow-hidden border-2 border-gray-200 rounded-lg group border-opacity-60 hover:ring-red-500 hover:ring-4 hover:ring-offset-4 hover:cursor-pointer">
                                            <img
                                                className="object-cover object-center w-full lg:h-72 md:h-48"
                                                src="https://i.imgur.com/0XKfojx.jpeg-/"
                                                alt=""
                                            />
                                            <div className="p-6 bg-red-500">
                                                <h1 className="mb-3 text-2xl font-semibold">
                                                    Projects
                                                </h1>
                                                <p className="mb-3 leading-relaxed">
                                                    Stock Analysis, ML & Programming
                                                </p>
                                            </div>
                                        </div>
                                    </motion.div>
                                </Link>
                                <Link href="/blog" className="p-4 sm:w-1/2 lg:w-1/4">
                                    <motion.div
                                        whileHover={{ scale: 1.05, rotate: -1, y: -30 }}
                                        whileTap={{ scale: 0.95 }}
                                    >
                                        <div className="h-full overflow-hidden border-2 border-gray-200 rounded-lg group border-opacity-60 hover:ring-red-500 hover:ring-4 hover:ring-offset-4 hover:cursor-pointer">
                                            <img
                                                className="object-cover object-center w-full lg:h-72 md:h-48"
                                                src="https://i.imgur.com/FdmL67w.jpeg"
                                                alt=""
                                            />
                                            <div className="p-6 bg-red-500">
                                                <h1 className="mb-3 text-2xl font-semibold">
                                                    Blog
                                                </h1>
                                                <p className="mb-3 leading-relaxed">
                                                    414 Kilometres away
                                                </p>
                                            </div>
                                        </div>
                                    </motion.div>
                                </Link>
                                <Link href="/founded" className="p-4 sm:w-1/2 lg:w-1/4">
                                    <motion.div
                                        whileHover={{ scale: 1.05, rotate: -2, y: -40 }}
                                        whileTap={{ scale: 0.95 }}
                                    >
                                        <div className="h-full overflow-hidden border-2 border-gray-200 rounded-lg group border-opacity-60 hover:ring-red-500 hover:ring-4 hover:ring-offset-4 hover:cursor-pointer">
                                            <img
                                                className="object-cover object-center w-full lg:h-72 md:h-48"
                                                src="https://i.imgur.com/jJWyQaX.jpeg"
                                                alt=""
                                            />
                                            <div className="p-6 bg-red-500">
                                                <h1 className="mb-3 text-2xl font-semibold">
                                                    Founded
                                                </h1>
                                                <p className="mb-3 leading-relaxed">
                                                    1,488 Kilometres away
                                                </p>
                                            </div>
                                        </div>
                                    </motion.div>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </motion.div>
        </>
    )
}
